const ejerciciosMaestros = [
  // PECHO
  ['PRESS DE BANCA', 'PECHO'], ['PRESS INCLINADO', 'PECHO'], ['PLANO CON MANC', 'PECHO'], 
  ['INCLINADO CON MANC', 'PECHO'], ['DECLINADO CON MANC', 'PECHO'], ['PLANO SENTADO HAMM', 'PECHO'], 
  ['PLANO HAMMER', 'PECHO'], ['PLANO SENTADO MAQ', 'PECHO'], ['INCLINADO EN HAMM', 'PECHO'], 
  ['DECLINADO EN HAMM', 'PECHO'], ['APERTURAS EN PECK DECK', 'PECHO'], ['APERTURAS EN POLEA', 'PECHO'], 
  ['PRESS EN POLEA', 'PECHO'], ['FLEXIONES', 'PECHO'], ['FONDOS', 'PECHO'], 
  ['CRUCES EN POLEA ALTA', 'PECHO'], ['CRUCES EN POLEA BAJA', 'PECHO'], ['PRESS DECLINADO', 'PECHO'], 
  ['PULLOVER MANCUERNA', 'PECHO'], ['PRESS PLANO BARRA', 'PECHO'], ['CRUCE DE POLEAS', 'PECHO'], ['PECK DECK', 'PECHO'],

  // ESPALDA
  ['JALON AL PECHO PRONO', 'ESPALDA'], ['JALON AL PECHO NEUTRO', 'ESPALDA'], ['JALON AL PECHO SUPINO', 'ESPALDA'], 
  ['JALON UNI EN POLEA', 'ESPALDA'], ['JALON EN HAMM', 'ESPALDA'], ['DOMINADAS PRONO', 'ESPALDA'], 
  ['DOMINADAS SUPINAS', 'ESPALDA'], ['REMO PRONO EN POLEA', 'ESPALDA'], ['REMO SUPINO EN POLEA', 'ESPALDA'], 
  ['REMO NEUTRO EN POLEA', 'ESPALDA'], ['REMO UNI EN POLEA', 'ESPALDA'], ['REMO DORIAN', 'ESPALDA'], 
  ['REMO CON BARRA', 'ESPALDA'], ['REMO EN HAMM', 'ESPALDA'], ['REMO EN T', 'ESPALDA'], 
  ['REMO EN MAQ', 'ESPALDA'], ['REMO EN SMITH', 'ESPALDA'], ['PULL OVER EN POLEA', 'ESPALDA'],
  ['SERRUCHO', 'ESPALDA'], ['TIRON AL PECHO SUPINO', 'ESPALDA'],

  // HOMBROS
  ['PRESS MILITAR CON MANC', 'HOMBROS'], ['PRESS MILITAR CON BARRA', 'HOMBROS'], ['PRESS MILITAR EN HAMM', 'HOMBROS'], 
  ['PRESS ARNOLD', 'HOMBROS'], ['VUELOS LAT CON MANC', 'HOMBROS'], ['VUELOS LAT EN MAQ', 'HOMBROS'], 
  ['VUELOS LAT EN POLEA', 'HOMBROS'], ['VUELOS FRONT CON MANC', 'HOMBROS'], ['VUELOS FRONT CON DISCO', 'HOMBROS'], 
  ['VUELOS FRONT EN POLEA', 'HOMBROS'], ['VUELOS FRONT C/ BARRA', 'HOMBROS'], ['REMO AL MENTON', 'HOMBROS'], 
  ['POSTERIOR CON MANC', 'HOMBROS'], ['POSTERIOR EN POLEA', 'HOMBROS'], ['POSTERIOR EN PECK DECK', 'HOMBROS'],
  ['VUELOS FRONTALES', 'HOMBROS'],

  // TRICEPS
  ['PRESS AGARRE CERRADO', 'TRICEPS'], ['EXTENSIONES CON BARRA', 'TRICEPS'], ['EXTENSIONES C/ CUERDA', 'TRICEPS'], 
  ['EXTENSIONES TRIANGULO', 'TRICEPS'], ['EXTENSIONES UNILATERAL', 'TRICEPS'], ['TRASNUCA EN POLEA', 'TRICEPS'], 
  ['TRASNUCA CON MANC', 'TRICEPS'], ['PRESS FRANCES MANC', 'TRICEPS'], ['PRESS FRANCES BARRA', 'TRICEPS'], 
  ['FONDOS EN PARALELA', 'TRICEPS'], ['FONDOS EN HAMMER', 'TRICEPS'], ['FONDOS EN BANCO', 'TRICEPS'],
  ['PRESS FRANCES', 'TRICEPS'], ['POLEA ALTA', 'TRICEPS'], ['PATADA DE BURRO', 'TRICEPS'],

  // BICEPS
  ['CURL BANCO INCLINADO', 'BICEPS'], ['CURL CON BARRA', 'BICEPS'], ['CURL CON BARRA W', 'BICEPS'], 
  ['CURL ALTERNADO MANC', 'BICEPS'], ['CURL EN SCOTT MANC', 'BICEPS'], ['CURL EN SCOTT BARRA', 'BICEPS'], 
  ['CURL SPIDER', 'BICEPS'], ['CURL HERCULES', 'BICEPS'], ['CURL PRONO CON BARRA', 'BICEPS'], 
  ['CURL PRONO EN POLEA', 'BICEPS'], ['CURL BAYESIAN', 'BICEPS'], ['CURL BAYESIAN UNI', 'BICEPS'], 
  ['CURL POLEA BAJA UNI', 'BICEPS'], ['CURL POLEA BAJA BARRA', 'BICEPS'], ['CURL MARTILLO', 'BICEPS'], 
  ['CURL EN MAQUINA', 'BICEPS'], ['CURL BARRA Z', 'BICEPS'], ['CONCENTRADO', 'BICEPS'], ['PREDICADOR', 'BICEPS'],

  // ZONA MEDIA
  ['CRUNCH', 'ZONA MEDIA'], ['CRUNCH EN POLEA', 'ZONA MEDIA'], ['CRUNCH EN BCO DECLI', 'ZONA MEDIA'], 
  ['ELVACION DE PIERNAS EN PISO', 'ZONA MEDIA'], ['ELEVACION DE PIERNAS EN PARALELAS', 'ZONA MEDIA'], 
  ['ROTACION DE TRONCO EN POLEA', 'ZONA MEDIA'], ['PRESS PALLOF', 'ZONA MEDIA'], 
  ['ROTACIONES CON DISCO EN EL PISO', 'ZONA MEDIA'], ['OBLICUOS CON DISCO', 'ZONA MEDIA'], 
  ['LUMBARES EN BANCO ROMANO', 'ZONA MEDIA'], ['LUMBARES EN EL PISO', 'ZONA MEDIA'], 
  ['PLANCHAS FRONTALES', 'ZONA MEDIA'], ['PLANCHAS LATERALES', 'ZONA MEDIA'], 
  ['PLANCHAS CON ROTACION', 'ZONA MEDIA'], ['PLANCHAS EN PELOTA', 'ZONA MEDIA'], 
  ['ESCALADORES', 'ZONA MEDIA'], ['BISAGRAS', 'ZONA MEDIA'], ['BISAGRAS UNILATERALES', 'ZONA MEDIA'], 
  ['BARQUITO', 'ZONA MEDIA'], ['TOQUES DE TOBILLO', 'ZONA MEDIA'], ['CRUNCH CRUZADO', 'ZONA MEDIA'],
  ['ABDOMINALES CRUNCH', 'ZONA MEDIA'], ['PLANCHA ISOMETRICA', 'ZONA MEDIA'], ['TWIST RUSO', 'ZONA MEDIA'],

  // TREN INFERIOR
  ['SENTADILLA CON BARRA', 'TREN INFERIOR'], ['SENTADILLA EN SMITH', 'TREN INFERIOR'], 
  ['SENTADILLA CON MANCUERNA', 'TREN INFERIOR'], ['SENTADILLA BULGARA', 'TREN INFERIOR'], 
  ['SENTADILLA FRONTAL', 'TREN INFERIOR'], ['SENTADILLA SUMO', 'TREN INFERIOR'], 
  ['SENTADILLA PISTOL', 'TREN INFERIOR'], ['SENTADILLA CON BANCO', 'TREN INFERIOR'], 
  ['SENTADILLA HACK', 'TREN INFERIOR'], ['SENTADILLA SISSY', 'TREN INFERIOR'], 
  ['PESO MUERTO CONVENCIONAL', 'TREN INFERIOR'], ['PESO MUERTO RUMANO', 'TREN INFERIOR'], 
  ['PESO MUERTO RUMANO UNILATERAL', 'TREN INFERIOR'], ['PESO MUERTO SUMO', 'TREN INFERIOR'], 
  ['ESTOCADAS ESTATICAS', 'TREN INFERIOR'], ['ESTOCADAS CAMINANDO', 'TREN INFERIOR'], 
  ['ESTOCADAS CON STEP', 'TREN INFERIOR'], ['ESTOCADAS EN SMITH', 'TREN INFERIOR'], 
  ['ESTOCADAS ATRÁS', 'TREN INFERIOR'], ['PRENSA 45', 'TREN INFERIOR'], ['PRENSA HORIZONTAL', 'TREN INFERIOR'], 
  ['EXTENSION DE CUADRICEPS', 'TREN INFERIOR'], ['CAMILLA DE ISQUIOS', 'TREN INFERIOR'], 
  ['BANCO DE ISQUIOS', 'TREN INFERIOR'], ['SENTADILLA EN BELT', 'TREN INFERIOR'], 
  ['ISQUIOS EN PELOTA', 'TREN INFERIOR'], ['ISQUIOS CON MANCUERNA', 'TREN INFERIOR'], 
  ['CURL NORDICO', 'TREN INFERIOR'], ['ELEVACIONES DE CADERA', 'TREN INFERIOR'], 
  ['PATADAS EN MAQUINA', 'TREN INFERIOR'], ['GEMELOS EN ESCALON', 'TREN INFERIOR'], 
  ['GEMELOS EN SMITH', 'TREN INFERIOR'], ['GEMELOS UNILATERALES', 'TREN INFERIOR'], 
  ['SOLEO', 'TREN INFERIOR'], ['PATADA DE GLUETEO EN POLEA', 'TREN INFERIOR'], 
  ['PATADA DE GLUTEOS CURZADA', 'TREN INFERIOR'], ['ABDUCTORES EN MAQUINA', 'TREN INFERIOR'], 
  ['ABDUCTORES EN POLEA', 'TREN INFERIOR'], ['ADUCTORES EN MAQUINA', 'TREN INFERIOR'], 
  ['ADUCTORES EN POLEA', 'TREN INFERIOR'], ['ADUCTORES CON PELOTA', 'TREN INFERIOR'],
  ['PRENSA', 'TREN INFERIOR'], ['ESTOCADAS', 'TREN INFERIOR']
];

const plantillasMaestras = [
  ['VARON 2 DIAS', 'Varón', 2], ['VARON 3 DIAS', 'Varón', 3], ['VARON 4 DIAS', 'Varón', 4], ['VARON 5 DIAS', 'Varón', 5],
  ['DAMA 2 DIAS', 'Dama', 2], ['DAMA 3 DIAS', 'Dama', 3], ['DAMA 4 DIAS', 'Dama', 4], ['DAMA 5 DIAS', 'Dama', 5]
];

module.exports = { ejerciciosMaestros, plantillasMaestras };
